export 'package:porfolio/screens/products/products_mobile.dart';
export 'package:porfolio/screens/products/products_tablet.dart';
export 'package:porfolio/screens/products/products_desktop.dart';
export 'package:porfolio/screens/resume/resume_mobile.dart';
export 'package:porfolio/screens/resume/resume_tablet.dart';
export 'package:porfolio/screens/resume/resume_desktop.dart';
export 'package:porfolio/screens/home/home_mobile.dart';
export 'package:porfolio/screens/home/home_tablet.dart';
export 'package:porfolio/screens/home/home_desktop.dart';
