name: Deploy Porfolio

on:
  push:
    branches:
      - demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PORT_APP: 80
      PORT_OUTSIDE: 8888
      CONTAINER_NAME: 'FRONTEND-CV'
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/frontend-cv
      IMAGE_TAG: latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
          # flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter --version

      - name: Enable Flutter Web
        run: flutter config --enable-web

      # - name: Run Tests
        # run: flutter test

      - name: Download Dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./build/web/*"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/var/www/cv/"
          SCRIPT_BEFORE: |
            sudo rm -R /var/www/cv/* || true
          SCRIPT_AFTER: |
            sudo service nginx restart